### ISSUE TITLE
Ability to change icon size

### ISSUE THREAD

**Issue by Syzygianinfern0** [Harshan01/Cloudflare-WARP-GNOME-Switcher#2]
The systray icon is a bit too large on my panel. Maybe an extension setting to change the icon size could be a possible solution. 

Also, it might be better to have an icon which is white (and not gray) so that it fits in better with the rest of the panel elements. Maybe one of [these](https://fontawesome.com/search?q=cloud) icons?

**Comment by Harshan01** [comment]
Hi, changing the default icon and size is simple change. Icons you linked look better.

As far extension settings, sounds like a great idea, even more for warp-cli settings. Eventually the idea is to make the extension a drop-down panel rather than a button as it is right now. Paired with extension settings, it could become a complete wrapper over warp-cli as like in Windows/Mac.

PRs are welcome

**Comment by Harshan01** [comment]
The icons are fixed in commit d682e67b5a07accb1717cbe31bf667766fdea625. There was an issue with the previous icon SVG which made it look like it did not fit the panel. Closing issue for now. Please reopen if the issue persists
